### ISSUE TITLE
editing a zettel in Emacs on Ubuntu/WSL

### ISSUE THREAD

**Issue by TheEditor** [AndrewCopeland/zettelkasten#10]
Doing a "./zk my-first" and firing emacs, editing and saving and exiting I get two files. A "blah-my-first.md" and "blah-my-first.md~". 

![2020 04 11 1150pm](https://user-images.githubusercontent.com/558011/79060106-34e67300-7c4f-11ea-9f80-8973adcaf724.png)

**Comment by AndrewCopeland** [comment]
It looks related to this issue:
https://stackoverflow.com/questions/2680389/how-to-remove-all-files-ending-with-made-by-emacs

emacs is creating this file as a temp file. Whats the content of each of these files? Are they the same?
I will push a fix to this right now though.

**Comment by TheEditor** [comment]
The content is the zettel template, before the edits I make.

Odd, this doesn't happen when I've used emacs for Lisp stuff.

**Comment by TheEditor** [comment]
Yeah, looking at that SO page you'd think there would be a way to set a flag *before* entering emacs that would alter that behavior. This is the kind of thing zk shouldn't have to worry about.

**Comment by AndrewCopeland** [comment]
Yeah it isn't however I added a quick clean up method after running an editor to resolve this issue.

The commit can be found here: https://github.com/AndrewCopeland/zettelkasten/commit/678740eef3e7efbe172d99353fe9d779ab951744

**Comment by AndrewCopeland** [comment]
I have a feeling this issue might occur with other editors so just removing the file seems to be the appropriate approach.

**Comment by TheEditor** [comment]
And that did the trick.

**Comment by AndrewCopeland** [comment]
Fantastic, thanks for all the feedback. I really appreciate it. I will close out this case now.
