### ISSUE TITLE
Curl installation command

### ISSUE THREAD

**Issue by bastiano** [AndrewCopeland/zettelkasten#33]
Hi, I run the curl command for installing zettelkasten in archlinux. The command has no output, and there is no zk or zettelkasten in /usr/local/bin.

**Comment by AndrewCopeland** [comment]
Does the following command output the zk script?
```
curl -s  https://raw.githubusercontent.com/AndrewCopeland/zettelkasten/master/zk
```

You may need to change the flag file here: 
```
-o /usr/local/bin/zk
```

The output should be a location within your `$PATH` environment variable.

Let me know if you still run into issues.

**Comment by bastiano** [comment]
It did work now. Thanks! I need to study how to configure it with Git. I like the "auto git push" feature, but I'm just starting with github.

**Comment by AndrewCopeland** [comment]
Let me know if you need any help with the `auto git push`. Create a new issue if you need help.
