### ISSUE TITLE
init on Ubuntu WSL

### ISSUE THREAD

**Issue by TheEditor** [AndrewCopeland/zettelkasten#9]
Upon the recent update, I zapped my .zettelkasten file and re-ran "zk init".
![2020 04 11 855pm](https://user-images.githubusercontent.com/558011/79058082-0361ad80-7c37-11ea-8007-15b4f0b2518d.png)

On first run my choice of dir was rejected. On attempt #2 I had no such problem, except the init sequence ran twice.

After that was able to do a "new first-zettel" no problem, getting in and out of emacs.

**Comment by rascoro1** [comment]
So just to validate, your zettelkasten directory is stored on your windows drive?
I have not tested this specific use case.

It also seems like you are getting weird behavior with the init command also.
I will test this out in my environment.

**Comment by rascoro1** [comment]
Do you think the directory should be automatically created if it does not exist?

**Comment by rascoro1** [comment]
I was not able to replicate the first issue. I was able to replicate the second issue which prompt for the init twice.

**Comment by TheEditor** [comment]
> Do you think the directory should be automatically created if it does not exist?

Don't know. But in this case the directory does exist. That's the odd thing.

**Comment by TheEditor** [comment]
And there is one other thing I neglected to mention. Not sure if this deserves a separate issue. See graphic:
![2020 04 11 1131pm](https://user-images.githubusercontent.com/558011/79059837-96591280-7c4c-11ea-9a03-49eb45798de9.png)

That first zettel has two entries. The regular .md file, and an ".md~" entry. This zettel was created via emacs, and I'm wondering if the line calling the editor in new() 

$ZETTELKASTEN_DEFAULT_TEXT_EDITOR +4 "$zettel_fname"

works right for emacs. After editing my zettel I closed out of emacs via C-x C-c.

**Comment by AndrewCopeland** [comment]
The duplicate prompt has been resolved in this commit: https://github.com/AndrewCopeland/zettelkasten/commit/bee30d3d86668716cd9501469540e9ac66e93f9f

The second issues should be placed in a seperare issue, so we could discuss there.

Are you able to replicate the first issue again?

**Comment by TheEditor** [comment]
Just dl'ed the update, zapped the config and zettels. First issue did not replicate and the duplicate prompt is gone.

But upon doing a "./zk my-first" and firing emacs, editing and saving I once again get two files. A "blah-my-first.md" and "blah-my-first.md~". I'll file another ticket.

**Comment by AndrewCopeland** [comment]
Awesome, thanks for testing. I will close out this issue.
